// <auto-generated />
using System;
using System.Collections;
using Infrastructure.Database.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(PfpTransactionsApiDatabaseContext))]
    partial class PfpTransactionsApiDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FundsCategory", b =>
                {
                    b.Property<int>("FundInternalId")
                        .HasColumnType("integer")
                        .HasColumnName("fund_internal_id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.HasKey("FundInternalId", "CategoryId")
                        .HasName("funds_categories_pkey");

                    b.HasIndex("CategoryId");

                    b.ToTable("funds_categories", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Database.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_date");

                    b.Property<BitArray>("IsDeleted")
                        .HasColumnType("bit(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_date");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("categories_pkey");

                    b.HasIndex(new[] { "Name" }, "categories_name_key")
                        .IsUnique();

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Database.Models.Fund", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_date");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<int?>("InternalId")
                        .IsRequired()
                        .HasColumnType("integer")
                        .HasColumnName("internal_id");

                    b.Property<BitArray>("IsDeleted")
                        .HasColumnType("bit(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("total_amount");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_date");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("funds_pkey");

                    b.HasIndex(new[] { "InternalId" }, "funds_internal_id_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Name" }, "funds_name_key")
                        .IsUnique();

                    b.ToTable("funds", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Database.Models.Limit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_date");

                    b.Property<int?>("InternalId")
                        .HasColumnType("integer")
                        .HasColumnName("internal_id");

                    b.Property<BitArray>("IsDeleted")
                        .HasColumnType("bit(1)")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_date");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("limits_pkey");

                    b.HasIndex("CategoryId");

                    b.HasIndex(new[] { "InternalId" }, "limits_internal_id_key")
                        .IsUnique();

                    b.ToTable("limits", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Database.Models.Recurrence", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_date");

                    b.Property<BitArray>("IsDeleted")
                        .HasColumnType("bit(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int?>("TransactionInternalId")
                        .HasColumnType("integer")
                        .HasColumnName("transaction_internal_id");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_date");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("recurrences_pkey");

                    b.HasIndex("TransactionInternalId");

                    b.ToTable("recurrences", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Database.Models.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_date");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<int?>("InternalId")
                        .IsRequired()
                        .HasColumnType("integer")
                        .HasColumnName("internal_id");

                    b.Property<BitArray>("IsDeleted")
                        .HasColumnType("bit(1)")
                        .HasColumnName("is_deleted");

                    b.Property<BitArray>("IsSplit")
                        .HasColumnType("bit(1)")
                        .HasColumnName("is_split");

                    b.Property<BitArray>("TransactionNotSplitInternalId")
                        .HasColumnType("bit(1)")
                        .HasColumnName("transaction_not_split_internal_id");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_date");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("transactions_pkey");

                    b.HasIndex(new[] { "InternalId" }, "transactions_internal_id_key")
                        .IsUnique();

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("TransactionsCategory", b =>
                {
                    b.Property<int>("TransactionInternalId")
                        .HasColumnType("integer")
                        .HasColumnName("transaction_internal_id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.HasKey("TransactionInternalId", "CategoryId")
                        .HasName("transactions_categories_pkey");

                    b.HasIndex("CategoryId");

                    b.ToTable("transactions_categories", (string)null);
                });

            modelBuilder.Entity("FundsCategory", b =>
                {
                    b.HasOne("Infrastructure.Database.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("fk__funds_categories__category_id__categories");

                    b.HasOne("Infrastructure.Database.Models.Fund", null)
                        .WithMany()
                        .HasForeignKey("FundInternalId")
                        .HasPrincipalKey("InternalId")
                        .IsRequired()
                        .HasConstraintName("fk__funds_categories__fund_internal_id__funds");
                });

            modelBuilder.Entity("Infrastructure.Database.Models.Limit", b =>
                {
                    b.HasOne("Infrastructure.Database.Models.Category", "Category")
                        .WithMany("Limits")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("fk__limits__category_id__categories");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Infrastructure.Database.Models.Recurrence", b =>
                {
                    b.HasOne("Infrastructure.Database.Models.Transaction", "TransactionInternal")
                        .WithMany("Recurrences")
                        .HasForeignKey("TransactionInternalId")
                        .HasPrincipalKey("InternalId")
                        .HasConstraintName("fk__recurrences__transaction_internal_id__transaction");

                    b.Navigation("TransactionInternal");
                });

            modelBuilder.Entity("TransactionsCategory", b =>
                {
                    b.HasOne("Infrastructure.Database.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("fk__transactions_categories__category_id__categories");

                    b.HasOne("Infrastructure.Database.Models.Transaction", null)
                        .WithMany()
                        .HasForeignKey("TransactionInternalId")
                        .HasPrincipalKey("InternalId")
                        .IsRequired()
                        .HasConstraintName("fk__transactions_categories__transaction_internal_id__transacti");
                });

            modelBuilder.Entity("Infrastructure.Database.Models.Category", b =>
                {
                    b.Navigation("Limits");
                });

            modelBuilder.Entity("Infrastructure.Database.Models.Transaction", b =>
                {
                    b.Navigation("Recurrences");
                });
#pragma warning restore 612, 618
        }
    }
}
